name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Download testsx
      run: |
        curl -o lab1_test.py https://nextcloud.citius.usc.es/s/4WLgdpcnzs9bp6g/download/test_lab1.py
    - name: test
      id: test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 20
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST_RESULTS: "${{steps.test.outputs.result}}"
      with:
        runners: test